name: SSH into Remote Machine
on:
  workflow_dispatch:
jobs:
  ssh_connect:
    runs-on: ubuntu-latest
    steps:
    - name: SSH into remote server
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSWORD }}
        script: echo "Successfully connected to the remote server!"
